name: changedetection
services:
  changedetection:
    image: ghcr.io/dgtlmoon/changedetection.io
    container_name: changedetection
    hostname: changedetection
    volumes:
      - changedetection-data:/datastore
    restart: unless-stopped
    environment:
        - PLAYWRIGHT_DRIVER_URL=ws://playwright-chrome:3000
        - USE_X_SETTINGS=1
    depends_on:
        playwright-chrome:
            condition: service_started
    ports:
      - "127.0.0.1:5000:5000"    
    networks:
      - detect
      # - traefik_global
    # labels:
      # - traefik.enable=true
      # - traefik.docker.network=traefik_global
      # - traefik.http.routers.crawl.rule=Host(`crawl.taiida.com`)
      # - traefik.http.services.crawl.loadbalancer.server.port=5000

  playwright-chrome:
    hostname: playwright-chrome
    image: docker.io/dgtlmoon/sockpuppetbrowser:latest
    cap_add:
      - SYS_ADMIN
    restart: unless-stopped
    environment:
      - SCREEN_WIDTH=1920
      - SCREEN_HEIGHT=1024
      - SCREEN_DEPTH=16
      - MAX_CONCURRENT_CHROME_PROCESSES=10
    networks:
      - detect

volumes:
  changedetection-data:

networks:
  # traefik_global:
  #   external: true
  detect:
