services:
  fail2ban:
    container_name: fail2ban_test
    restart: always
    image: crazymax/fail2ban:latest
    environment:
      - F2B_DB_PURGE_AGE=30d
      - F2B_LOG_TARGET=/data/fail2ban.log
      - F2B_LOG_LEVEL=INFO
      - F2B_IPTABLES_CHAIN=INPUT
    volumes:
      - fail2ban:/data
#    network_mode: "host"
#    privileged: true
    cap_add:
      - NET_ADMIN
#      - NET_RAW
volumes:
  fail2ban:
    name: fail2ban_test
