services:
  miniflux:
    image: ghcr.io/miniflux/miniflux:latest
    container_name: miniflux
    depends_on:
      db:
        condition: service_healthy
    environment:
      - DATABASE_URL=postgres://${PG_USER}:${PG_PASS}@db:5432/${PG_DB}?sslmode=disable
      - RUN_MIGRATIONS=1
      - CREATE_ADMIN=1
      - ADMIN_USERNAME=${MINIFLUX_ADMIN}
      - ADMIN_PASSWORD=${MINIFLUX_ADMIN_PASS}
      - BASE_URL=${MINIFLUX_DOMAIN}
    networks:
      - miniflux
      - traefik_global
    # ports:
    #  - 127.0.0.1:8080:8080
    labels:
      - traefik.enable=true
      - traefik.docker.network=traefik_global
      - traefik.http.routers.miniflux.rule=Host(`${MINIFLUX_HOST}`)
      - traefik.http.routers.miniflux.service=miniflux
      - traefik.http.services.miniflux.loadbalancer.server.port=8080
  db:
    image: postgres:17
    container_name: miniflux_db
    environment:
      - POSTGRES_USER=${PG_USER}
      - POSTGRES_PASSWORD=${PG_PASS}
      - POSTGRES_DB=${PG_DB}
    volumes:
      - db:/var/lib/postgresql/data
      # - /home/naokiiida/volumes/miniflux_miniflux-db:/pg15
    healthcheck:
      test: ["CMD", "pg_isready", "-U", "${PG_USER}"]
      interval: 10s
      start_period: 30s
    networks:
      - miniflux
volumes:
  db:
networks:
  miniflux:
  traefik_global:
    external: true  
