services:
  openhands-app:
    image: docker.all-hands.dev/all-hands-ai/openhands:0.36
    container_name: openhands-app
    restart: unless-stopped
    environment:
      SANDBOX_RUNTIME_CONTAINER_IMAGE: docker.all-hands.dev/all-hands-ai/runtime:0.36-nikolaik
      LOG_ALL_EVENTS: "true"
    ports:
      - "3000:3000"
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
      - ~/.openhands-state:/.openhands-state
    extra_hosts:
      - "host.docker.internal:host-gateway"
    stdin_open: true
    tty: true
    labels:
      - dev.orbstack.domains=openhands.local

