services:
  vaultwarden:
    image: ghcr.io/dani-garcia/vaultwarden:latest
    container_name: vaultwarden
    restart: unless-stopped
    networks:
      - "traefik_global"
    environment:
      DOMAIN: ${VAULT_DOMAIN}
      SHOW_PASSWORD_HINT: false
      SIGNUPS_ALLOWED: false
      # ADMIN_TOKEN: ${VAULTWARDEN_ADMIN_TOKEN}
      PUSH_ENABLED: true
      PUSH_INSTALLATION_ID: ${PUSH_ID}
      PUSH_INSTALLATION_KEY: ${PUSH_KEY}
      LOG_FILE: /data/vaultwarden.log
    volumes:
      - vaultwarden-data:/data/
    labels:
      - traefik.enable=true
      - traefik.http.routers.bitwarden.rule=Host(`${VAULT_HOST}`)
      - traefik.http.routers.bitwarden.service=bitwarden
      - traefik.http.services.bitwarden.loadbalancer.server.port=80

  fail2ban:
    container_name: fail2ban
    restart: always
    image: crazymax/fail2ban:latest
    environment:
      - TZ=Japan
      - F2B_DB_PURGE_AGE=30d
      - F2B_LOG_TARGET=/data/fail2ban.log
      - F2B_LOG_LEVEL=INFO
      - F2B_IPTABLES_CHAIN=INPUT
    volumes:
      - fail2ban:/data
      - vaultwarden-data:/vaultwarden:ro
    network_mode: "host"
    privileged: true
    cap_add:
      - NET_ADMIN
      - NET_RAW

  backup:
    image: ttionya/vaultwarden-backup:latest
    restart: always
    # environment:
    #   RCLONE_REMOTE_NAME: 'BitwardenBackup'
    #   RCLONE_REMOTE_DIR: '/BitwardenBackup/'
    #   RCLONE_GLOBAL_FLAG: ''
    #   CRON: '5 * * * *'
    #   ZIP_ENABLE: 'TRUE'
    #   ZIP_PASSWORD: ${ZIP_PASSWORD}
    #   ZIP_TYPE: 'zip'
    #   BACKUP_FILE_SUFFIX: '%Y%m%d'
    #   BACKUP_KEEP_DAYS: 0
    #   PING_URL: ''
    #   MAIL_SMTP_ENABLE: 'FALSE'
    #   MAIL_SMTP_VARIABLES: ''
    #   MAIL_TO: ''
    #   MAIL_WHEN_SUCCESS: 'TRUE'
    #   MAIL_WHEN_FAILURE: 'TRUE'
    #   TIMEZONE: 'UTC'
    volumes:
      - vaultwarden-data:/bitwarden/data/
      - vaultwarden-rclone-data:/config/
    #   - /path/to/env:/.env

volumes:
  vaultwarden-rclone-data:
    external: true
    name: vaultwarden-rclone-data
  vaultwarden-data:
    name: vaultwarden-data
  fail2ban:
    external: true
    name: fail2ban

networks:
  traefik_global:
    external: true
