services:
  vaultwarden:
    image: ghcr.io/dani-garcia/vaultwarden:latest
    container_name: vaultwarden
    restart: unless-stopped
    networks:
      - "traefik_global"
    environment:
      WEBSOCKET_ENABLED: true  # Enable WebSocket notifications.
      DOMAIN: "https://bitwarden.taiida.com"
    volumes:
      - /home/digital/Documents/vaultwarden/data:/data:Z
    labels:
      - traefik.enable=true
      #- traefik.http.routers.bitwarden-ui.entrypoints=https
      #- traefik.http.routers.bitwarden-ui.tls.certresolver=letsencrypt
      - traefik.http.routers.bitwarden-ui.rule=Host(`bitwarden.taiida.com`)
      - traefik.http.routers.bitwarden-ui.service=bitwarden-ui
      - traefik.http.services.bitwarden-ui.loadbalancer.server.port=80
      - traefik.http.routers.bitwarden-websocket.rule=Host(`bitwarden.taiida.com`) && Path(`/notifications/hub`)
      - traefik.http.routers.bitwarden-websocket.service=bitwarden-websocket
      - traefik.http.services.bitwarden-websocket.loadbalancer.server.port=3012

networks:
  traefik_global:
    external: true
