services:
  vaultwarden:
    image: ghcr.io/dani-garcia/vaultwarden:latest
    container_name: vaultwarden
    restart: unless-stopped
    networks:
      - "traefik_global"
    environment:
      DOMAIN: "https://bitwarden.taiida.com"
      SHOW_PASSWORD_HINT: false
      SIGNUPS_ALLOWED: false
      # ADMIN_TOKEN: ${VAULTWARDEN_ADMIN_TOKEN}
      PUSH_ENABLED: true
      PUSH_INSTALLATION_ID: ${PUSH_ID}
      PUSH_INSTALLATION_KEY: ${PUSH_KEY}
    volumes:
      - /home/digital/Documents/vaultwarden/data:/data:Z
    labels:
      - traefik.enable=true
      - traefik.http.routers.bitwarden.rule=Host(`bitwarden.taiida.com`)
      - traefik.http.routers.bitwarden.service=bitwarden
      - traefik.http.services.bitwarden.loadbalancer.server.port=80

networks:
  traefik_global:
    external: true
