version: "3.8"

services:
  zitadel-external-tls:
    image: "ghcr.io/zitadel/zitadel:stable"
    command: 'start-from-init --masterkey "MasterkeyNeedsToHave32Characters"'
    environment:
      - ZITADEL_EXTERNALDOMAIN=zitadel.taiida.com
      - ZITADEL_EXTERNALPORT=443
      - ZITADEL_EXTERNALSECURE=true
      - ZITADEL_TLS_ENABLED=external
      # database configuration
      - ZITADEL_DATABASE_POSTGRES_HOST=db
      - ZITADEL_DATABASE_POSTGRES_PORT=5432
      - ZITADEL_DATABASE_POSTGRES_DATABASE=zitadel
      - ZITADEL_DATABASE_POSTGRES_USER_USERNAME=zitadel_user
      - ZITADEL_DATABASE_POSTGRES_USER_PASSWORD=zitadel_pw
      - ZITADEL_DATABASE_POSTGRES_USER_SSL_MODE=disable
      - ZITADEL_DATABASE_POSTGRES_ADMIN_USERNAME=root
      - ZITADEL_DATABASE_POSTGRES_ADMIN_PASSWORD=postgres
      - ZITADEL_DATABASE_POSTGRES_ADMIN_SSL_MODE=disable
      - ZITADEL_LOGSTORE_ACCESS_STDOUT_ENABLED=true
    networks:
      - "zitadel"
      - "traefik_global"
    depends_on:
      db:
        condition: "service_healthy"
    hostname: zitadel.taiida.com
    container_name: zitadel
    labels:
      - traefik.enable=true
      - traefik.http.routers.zitadel.rule=Host(`zitadel.taiida.com`)
      - "traefik.http.routers.zitadel.rule=PathPrefix(`/`)"
      - traefik.http.routers.zitadel.service=zitadel
      - "traefik.http.services.zitadel.loadbalancer.server.port=8080"
      - "traefik.http.services.zitadel.loadbalancer.server.scheme=h2c"
      - "traefik.http.services.zitadel.loadbalancer.server.url=zitadel-external-tls"
    healthcheck:
      test: ["CMD", "/app/zitadel", "ready"]
      interval: "10s"
      timeout: "5s"
      retries: 5
      start_period: "10s"

  db:
    restart: "always"
    image: postgres:16-alpine
    environment:
      - POSTGRES_USER=root
      - POSTGRES_PASSWORD=postgres
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -d zitadel"]
      interval: 5s
      timeout: 60s
      retries: 10
      start_period: 5s
#    ports:
#     - "5432:5432"
    networks:
      - "zitadel"
    volumes:
      - "zitadel_data:/var/lib/postgresql/data:rw"

volumes:
  zitadel_data:
    #    external: true

networks:
  zitadel:
  traefik_global:
    external: true
